import { expect, test } from "@playwright/test";
import { connectAccount, createWorkspace, newContext, signUp, waitForSync } from "./helpers";

test("nontechnical journey: priorities, budgets, projects, teamwork, guides and digest", async ({ browser }) => {
  const ctx = await newContext(browser), page = await ctx.newPage();
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  await signUp(page,"Taylor Owner"); await createWorkspace(page,"Everyday Cloud");
  await expect(page.getByRole("heading",{name:"Your cloud, made clearer."})).toBeVisible();
  await expect(page.getByText("Connect an AWS account to get started").filter({ visible: true })).toBeVisible();
  await connectAccount(page); await waitForSync(page);
  await page.goto("/");
  await expect(page.getByRole("heading",{name:"What needs your attention"})).toBeVisible();
  await expect(page.getByRole("link",{name:"Servers EC2"})).toBeVisible();
  await expect(page.getByRole("img", {name:/Spending trend/})).toBeVisible();
  await expect(page.getByRole("img", {name:/open security findings/})).toBeVisible();
  await expect(page.getByRole("list", {name:"Resources by category"})).toBeVisible();
  await page.getByRole("button", {name:"7 days",exact:true}).click();
  await expect(page.getByRole("button", {name:"7 days",exact:true})).toHaveAttribute("aria-pressed","true");
  await page.getByRole("button", {name:"Show Spending trend as table"}).click();
  await expect(page.getByRole("table", {name:"Spending trend data"}).getByRole("row")).toHaveCount(8);
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", {name:"Download CSV"}).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("spending-7-days.csv");
  await page.getByRole("button", {name:"Show Spending trend as chart"}).click();
  await page.getByRole("button", {name:"30 days",exact:true}).click();
  await page.screenshot({path:"test-results/screens/simple-home.png",fullPage:true});
  await page.getByText("Explain this",{exact:true}).filter({ visible: true }).first().click();
  await expect(page.getByText(/This is the usage spending AWS reported/).filter({ visible: true })).toBeVisible();
  await page.getByRole("button",{name:"Switch to detailed mode"}).click();
  await expect(page.getByText("EC2 instances").filter({ visible: true }).first()).toBeVisible();
  await page.reload(); await expect(page.getByRole("button",{name:"Switch to simple mode"})).toBeVisible();
  await page.getByRole("button",{name:"Switch to simple mode"}).click();
  await expect(page.getByRole("heading",{name:"Your cloud, made clearer."})).toBeVisible();
  await page.goto("/budget");
  await page.getByLabel("Monthly budget",{exact:true}).filter({ visible: true }).fill("5000");
  await page.getByLabel("Currency code").filter({ visible: true }).fill("USD");
  await page.getByRole("button",{name:"Save monthly budget"}).click();
  await expect(page.getByText("Monthly budget saved").filter({ visible: true })).toBeVisible();
  await page.reload(); await expect(page.getByLabel("Monthly budget",{exact:true}).filter({ visible: true })).toHaveValue("5000");
  await page.screenshot({path:"test-results/screens/simple-budget.png",fullPage:true});
  await page.goto("/projects");
  await page.getByRole("button",{name:"Create business project"}).click();
  await page.getByLabel("Project name").filter({ visible: true }).fill("Company website");
  await page.getByLabel("Person or team responsible").filter({ visible: true }).fill("Website team");
  await page.getByRole("checkbox",{name:"Production"}).check();
  await page.getByRole("button",{name:"Save project"}).click();
  await expect(page.getByRole("heading",{name:"Company website"})).toBeVisible();
  await page.reload(); await expect(page.getByText("Responsible: Website team").filter({ visible: true })).toBeVisible();
  await page.screenshot({path:"test-results/screens/simple-projects.png",fullPage:true});
  await page.goto("/");
  await page.getByRole("link",{name:"Ask a teammate"}).first().click();
  await page.getByLabel("Assign to").filter({ visible: true }).selectOption({label:"Taylor Owner"});
  await page.getByLabel("What do you need help with?").filter({ visible: true }).fill("Please review the affected resource before changing it.");
  await page.getByRole("button",{name:"Assign help request"}).click();
  await expect(page.getByText("Help request assigned in Stratus").filter({ visible: true })).toBeVisible();
  await expect(page.getByText("Assigned to Taylor Owner").filter({ visible: true })).toBeVisible();
  await page.getByRole("button",{name:"Mark request complete"}).click();
  await expect(page.getByRole("button",{name:"Reopen request"})).toBeVisible();
  await page.goto("/weekly?week=0");
  await expect(page.getByRole("heading",{name:"Weekly summary"})).toBeVisible();
  await expect(page.getByText("Team requests completed").filter({ visible: true }).locator("../..")).toContainText("1");
  await page.screenshot({path:"test-results/screens/simple-weekly.png",fullPage:true});
  await page.goto("/start");
  await page.getByRole("button",{name:/Store my files/}).click();
  await expect(page.getByRole("heading",{name:"Your plan: store my files"})).toBeVisible();
  await page.getByRole("link",{name:"Open step-by-step setup"}).click();
  await page.getByText("Before making this change",{exact:true}).filter({ visible: true }).click();
  await expect(page.getByText("Expected result:").filter({ visible: true })).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  for (const path of ["/", "/budget", "/projects", "/help", "/weekly", "/start"]) {
    await page.goto(path);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({path:`test-results/screens/mobile-${path.slice(1)||"home"}.png`,fullPage:true});
  }
  await page.setViewportSize({width:1440,height:900});
  await page.goto("/");
  await page.getByRole("button",{name:"Account menu"}).click();
  await page.getByRole("menuitemradio",{name:"Dark",exact:true}).click();
  await expect(page.locator("html")).toHaveClass(/dark/);
  await page.screenshot({path:"test-results/screens/simple-home-dark.png",fullPage:true});
  expect(errors).toEqual([]);
  await ctx.close();
});
