"use client";
import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Explain } from "./explain";
const goals = [
  { id: "files", title: "Store my files", guide: "s3-create-bucket", result: "A private file-storage space in Amazon S3.", settings: "Keep public access blocked, enable version history, and use encryption.", costs: "Storage, file requests, and downloads can create charges. Older file versions also use paid storage. A useful estimate needs your expected storage and usage.", impact: "Creates new storage; it does not move or back up your existing files automatically.", undo: "Copy out files you need before removing storage. Permanent deletion cannot be undone." },
  { id: "app", title: "Run my application", guide: "ec2-launch-instance", result: "A virtual server in Amazon EC2. You or your technical teammate still need to install and configure your application.", settings: "Start with a small server, encrypted storage, and private network access. Ask your technical teammate how users will reach the application.", costs: "A running server is billed even when nobody uses the app. Disks and public IP addresses can add charges. Review the regional estimate before creating it.", impact: "Creates a new server. It does not deploy your app, move traffic, or configure a domain.", undo: "Back up required data before terminating a server. Disks may be deleted with it; stopping a server does not stop all charges." },
  { id: "database", title: "Store my application’s data", guide: "rds-create-database", result: "A managed relational database in Amazon RDS.", settings: "Use a private database, encryption, and automated backups. Confirm the database engine with your application’s developer.", costs: "Database capacity, storage, and backups may be billed even while your application is idle. High-availability options cost more. Review AWS’s current estimate in the creation screen.", impact: "Creates a database. Moving your app’s data or switching its connection can require a separate migration and downtime.", undo: "Create and verify a backup before deleting the database. Restoring a backup takes time and does not recover changes made after it." },
  { id: "security", title: "Make my account safer", guide: null, result: "A prioritized list of security settings to review in your connected accounts.", settings: "Start with urgent findings, read the evidence, and ask a technical teammate when the impact is unclear.", costs: "Some fixes affect paid resources or data transfer. Check the specific finding and its walkthrough for cost implications.", impact: "Restricting access can interrupt legitimate users and applications. Review who depends on the resource before changing it.", undo: "Record the existing settings first. Each walkthrough explains recovery where possible; restoring exposed access can reintroduce risk." },
];
export function StartTask({ canReadSecurity }: { canReadSecurity: boolean }) {
  const [selected,setSelected] = useState<string | null>(null);
  const goal = goals.find(g => g.id === selected);
  return <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-2">{goals.filter(g => g.id !== "security" || canReadSecurity).map(g => <button type="button" key={g.id} aria-pressed={selected === g.id} className={`rounded-xl border p-5 text-left transition-colors hover:bg-muted ${selected === g.id ? "border-primary bg-primary/5 ring-1 ring-primary" : "bg-card"}`} onClick={() => setSelected(g.id)}><span className="font-semibold">{g.title}</span><p className="mt-2 text-sm text-muted-foreground">{g.result}</p></button>)}</div>
    {goal && <section className="space-y-4 rounded-xl border bg-card p-6" aria-live="polite"><h2 className="text-xl font-semibold">Your plan: {goal.title.toLowerCase()}</h2><dl className="space-y-4 text-sm">{[["Recommended starting settings",goal.settings],["What it may cost",goal.costs],["What will change",goal.impact],["Can I undo it?",goal.undo]].map(([label,text]) => <div key={label}><dt className="font-semibold">{label}</dt><dd className="mt-1 leading-relaxed text-muted-foreground">{text}</dd></div>)}</dl><Button asChild><Link href={goal.guide ? `/guides/${goal.guide}` : "/security"}>{goal.guide ? "Open step-by-step setup" : "Review my security findings"}</Link></Button><p className="text-xs text-muted-foreground">Choosing a goal does not create or modify AWS resources.</p></section>}
    <Explain label="New to cloud services?"><p>A server runs your application. File storage holds uploads and documents. A database stores structured information such as orders or user records. A network controls how these services can communicate.</p><p>You can start with a walkthrough and ask a technical teammate to help with settings. Use the final review screen to check the account, region, costs, and effects before creating anything.</p></Explain>
  </div>;
}
