"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { CloudConnectionDto, CloudProvider } from "@/lib/cloud";
import { api, errorMessage } from "@/lib/api-client";
import { formatCurrency, formatDateTime } from "@/lib/format";
import { fillDays } from "@/lib/cost-math";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { ChartCard } from "@/components/charts/chart-card";
import { ColumnChart } from "@/components/charts/column-chart";
import { BarList } from "@/components/charts/bar-list";
import { ConnectCloud } from "./connect-cloud";

export function CloudDashboard({orgId,provider,connections,canConnect,canSync,canDisconnect,canInventory,canCost,canSecurity}:{orgId:string;provider:CloudProvider;connections:CloudConnectionDto[];canConnect:boolean;canSync:boolean;canDisconnect:boolean;canInventory:boolean;canCost:boolean;canSecurity:boolean}) {
  const router=useRouter(),[showConnect,setShowConnect]=useState(false),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState("all"),[search,setSearch]=useState(""),[currency,setCurrency]=useState(""),[tab,setTab]=useState("inventory");
  const view = (tab === "inventory" && canInventory) || (tab === "billing" && canCost) || (tab === "security" && canSecurity) ? tab : canInventory ? "inventory" : canCost ? "billing" : "security";
  const visible=connections.filter(c=>selected === "all" || c.id === selected);
  const resources=visible.flatMap(c=>(c.inventory??[]).map(r=>({...r,connection:c.displayName,connectionId:c.id})));
  const filtered=resources.filter(r=>`${r.name} ${r.type} ${r.region} ${r.id}`.toLowerCase().includes(search.toLowerCase()));
  const findings=visible.flatMap(c=>(c.security??[]).map(f=>({...f,connection:c.displayName,connectionId:c.id})));
  const costs=visible.flatMap(c=>c.billing??[]),currencies=[...new Set(costs.map(c=>c.currency))].sort();
  const unit=currencies.includes(currency)?currency:currencies[0];
  const now=new Date(),end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+1)),start=new Date(end.getTime()-30*86400000);
  const selectedCosts=costs.filter(c=>c.currency === unit && c.day>=start.toISOString().slice(0,10) && c.day<end.toISOString().slice(0,10)), totals=new Map<string,number>();
  for(const c of selectedCosts)totals.set(c.day,(totals.get(c.day)??0)+c.amount);
  const daily=fillDays([...totals].map(([day,amount])=>({day,amount,estimated:true})),start,end);
  const types=new Map<string,number>();for(const r of resources)types.set(r.type,(types.get(r.type)??0)+1);
  const savedAt=(value:string|null)=>value?formatDateTime(value):"Not synced";
  async function action(id:string,method:"POST"|"DELETE") {setBusy(id);setError(null);try{await api(`/api/v1/orgs/${orgId}/cloud-connections/${id}`,{method});router.refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(null);}}
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><label className="text-sm">Connection <select aria-label="Cloud connection" value={selected} onChange={e=>setSelected(e.target.value)} className="ml-2 max-w-full rounded-md border bg-background p-2"><option value="all">All {provider} connections</option>{connections.map(c=><option key={c.id} value={c.id}>{c.displayName}</option>)}</select></label>{canConnect&&<Button onClick={()=>setShowConnect(!showConnect)} variant={showConnect?"outline":"default"}>{showConnect?"Close setup":`Connect ${provider}`}</Button>}</div>
    {(showConnect||!connections.length)&&canConnect&&<ConnectCloud orgId={orgId} provider={provider}/>}
    {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
    <div className="grid gap-3 lg:grid-cols-2">{visible.map(c=><Card key={c.id}><CardHeader><CardTitle>{c.displayName}</CardTitle><p className="break-all text-xs text-muted-foreground">{c.externalId} · {c.status.replaceAll("_"," ")}</p></CardHeader><CardContent className="space-y-3"><dl className="space-y-1 text-xs text-muted-foreground">{canInventory&&<div>Inventory: {savedAt(c.inventoryAt)}</div>}{canCost&&<div>Billing: {savedAt(c.billingAt)}</div>}{canSecurity&&<div>Security: {savedAt(c.securityAt)}</div>}</dl>{Object.entries(c.diagnostics).filter(([,v])=>v!=="Ready").map(([k,v])=><p key={k} className="text-xs text-amber-700 dark:text-amber-300">{k}: {v} Previous saved data, if any, remains visible.</p>)}{c.status === "DISCONNECTED"&&<p className="text-xs text-muted-foreground">Historical data only. Credentials were removed from Stratus. Revoke the key or secret in your cloud portal if it is no longer needed.</p>}<div className="flex flex-wrap gap-2">{canSync&&c.status!=="DISCONNECTED"&&<Button size="sm" variant="outline" disabled={busy!==null} onClick={()=>void action(c.id,"POST")}>{busy===c.id?"Working…":"Refresh cloud data"}</Button>}{canDisconnect&&c.status!=="DISCONNECTED"&&<details className="text-xs"><summary className="cursor-pointer py-2 text-muted-foreground">Disconnect</summary><p className="py-2">Remove saved credentials and stop refreshing. Cloud resources remain unchanged; saved data is retained.</p><Button size="sm" variant="outline" disabled={busy!==null} onClick={()=>void action(c.id,"DELETE")}>Confirm disconnect</Button></details>}</div></CardContent></Card>)}</div>
    {!!connections.length&&<>
      <div role="group" aria-label="Cloud data views" className="flex gap-2 border-b pb-3">{[["inventory","Resources",canInventory],["billing","Spending",canCost],["security","Security",canSecurity]].filter(([, ,allowed])=>allowed).map(([value,label])=><Button key={String(value)} variant={view===value?"secondary":"ghost"} aria-pressed={view===value} onClick={()=>setTab(String(value))}>{label}</Button>)}</div>
      {view==="inventory"&&canInventory&&<div className="space-y-4"><ChartCard title="Resources by type" description={`${resources.length} resources in saved snapshots`} state={resources.length?{kind:"ready"}:{kind:"empty",message:"No inventory yet, or the completed snapshot contains no resources. Check the connection status above."}} height={260}><BarList ariaLabel="Cloud resource types" items={[...types].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value])=>({label,value,display:String(value)}))}/></ChartCard><Input aria-label="Search cloud resources" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, service, region or resource ID"/><p className="text-xs text-muted-foreground">{filtered.length} matching resources. Showing the first 200; narrow the search for more.</p><div className="overflow-auto rounded-lg border"><table className="w-full text-left text-sm"><thead><tr>{["Resource","Type","Location","Connection"].map(h=><th key={h} scope="col" className="p-3">{h}</th>)}</tr></thead><tbody>{filtered.slice(0,200).map(r=><tr key={`${r.connectionId}:${r.id}`} className="border-t"><td className="max-w-80 break-all p-3">{r.name}<details className="text-xs text-muted-foreground"><summary>Resource ID</summary>{r.id}</details></td><td className="max-w-64 break-all p-3">{r.type}</td><td className="p-3">{r.region}</td><td className="p-3">{r.connection}</td></tr>)}</tbody></table></div></div>}
      {view==="billing"&&canCost&&<div className="space-y-4"><p className="text-sm text-muted-foreground">Last 30 days, from saved billing snapshots. Estimates may arrive late. {provider==="GCP"?"Usage costs before credits and invoice adjustments.":"Pre-tax usage cost; final invoices may differ."} Currencies are never combined. Missing days appear as gaps.</p><label className="text-sm">Billing currency <select className="ml-2 rounded border bg-background p-2" aria-label="Billing currency" value={unit??""} onChange={e=>setCurrency(e.target.value)}>{currencies.length?currencies.map(c=><option key={c}>{c}</option>):<option value="">No billing data</option>}</select></label><ChartCard title="Cloud spending" description={unit?formatCurrency(selectedCosts.reduce((s,c)=>s+c.amount,0),unit):"Billing is not available"} state={selectedCosts.length?{kind:"ready"}:{kind:"empty",message:"No billing data is available. Check permissions, export configuration and the billing sync status above."}} summary={`${selectedCosts.length} reported daily amounts in ${unit??"no currency"}`} table={<table className="w-full text-left text-xs"><thead><tr><th>Date</th><th>Amount</th></tr></thead><tbody>{daily.map(d=><tr key={d.day}><td className="py-1">{d.day}</td><td>{d.amount===null?"Unavailable":formatCurrency(d.amount,unit??null)}</td></tr>)}</tbody></table>}><ColumnChart data={daily.map(d=>({x:d.day,y:d.amount,estimated:true}))} unit="count" label="Usage cost" formatX={day=>day.slice(5)} formatY={n=>formatCurrency(n,unit??null)}/></ChartCard></div>}
      {view==="security"&&canSecurity&&<div className="space-y-3"><p className="text-sm text-muted-foreground">{findings.length} open findings in saved snapshots. This view imports {provider==="GCP"?"global Security Command Center findings":"unhealthy Defender for Cloud assessments"}; it does not perform its own scan. No findings is not a security guarantee.</p>{findings.length?findings.slice(0,200).map(f=><Card key={`${f.connectionId}:${f.id}`}><CardContent><p className="text-xs text-muted-foreground">{f.severity} · {f.connection}</p><h2 className="mt-1 font-medium">{f.title}</h2><p className="mt-2 break-all text-xs text-muted-foreground">{f.resource}</p></CardContent></Card>):<p>Check the security sync status above to distinguish an empty result from unavailable access.</p>}{findings.length>200&&<p className="text-xs text-muted-foreground">Showing 200 findings. Select an individual connection to narrow the view.</p>}</div>}
    </>}
  </div>;
}
