"use client";

import Link from "next/link";
import { useState, type ReactNode, type FormEvent } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { toast } from "sonner";
import { api, errorMessage } from "@/lib/api-client";
import { hasPermission, type Role } from "@/lib/rbac";
import { WRITE_PERMISSION, interpretInventorySearch, type RecordKind } from "@/lib/operations";
import { backupReadiness, relatedResources, costSpikes, type OpsResource, type OpsCost } from "@/lib/operations-insights";
import type { CloudConnectionDto } from "@/lib/cloud";
import { resourceHref } from "@/lib/resource-links";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { HelpStatus } from "@/components/simple/help";
import { CreateResource } from "@/components/aws/create-resource";

interface SavedItem { id: string; kind: RecordKind; name: string; userId: string; shared: boolean; payload: Record<string, unknown>; resourceId: string | null; version: number; createdAt: string }
interface Change { id: string; resourceId: string; kind: string; before: unknown; after: unknown; observedAt: string }
interface Plan { id: string; name: string; userId: string; status: string; payload: { action: string; tags: { key: string; value: string }[]; timezone: string; snapshots: { id: string; name: string; resourceId: string; before: unknown }[] }; scheduledAt: string | null; expiresAt: string; result: unknown }
export interface HubData {
  records: SavedItem[]; resources: OpsResource[]; changes: Change[]; clouds: CloudConnectionDto[]; costs: OpsCost[];
  priorities: { actions: { id: string; title: string; reason: string; href: string; priority: string; kind: string }[]; accounts: { id: string; displayName: string; syncStatus: string; lastSyncedAt: string | null }[] };
  help: { id: string; title: string; assigneeId: string; requestedById: string; note: string; status: string; assignee?: { name: string }; kind: string }[];
  findings: { id: string; title: string; awsAccountRefId: string }[];
  members: { userId: string; role: Role; user: { name: string } }[];
  plans: Plan[]; deliveries: { id: string; status: string; attempts: number; message: string | null; updatedAt: string }[];
  org: { requiredTagKeys: string[]; actionModeEnabled: boolean }; rules: { id: string; name: string }[];
  baselines: { id: string; name: string; resourceId: string; changes: string[]; observed: boolean; before: unknown; after: unknown; capturedAt: string }[];
  savings: { id: string; after: { currency: string; amount: number; days: number; estimated: boolean }[]; complete: boolean }[];
  security: { id: string; title: string; resourceRefId: string | null; severity: string }[];
  metrics: { resourceRefId: string; metricName: string; value: number | null; collectedAt: string }[];
  credentials: { id: string; displayName: string; securityScannedAt: string | null; securityCoverage: { credentialMetadata?: { userName: string; keyHint: string; ageDays: number; active: boolean }[] | null } | null }[];
  truncated: boolean;
}
const tabs = ["Overview", "Resources", "Reliability", "Costs", "Team", "Automation", "Templates", "Notifications"] as const;
type Tab = typeof tabs[number];
const control = "w-full rounded-md border bg-background p-2 text-sm";
const date = (value: string | null) => value ? new Date(value).toLocaleString() : "Not observed";
function Box({ title, children }: { title: string; children: ReactNode }) { return <section className="space-y-3 rounded-xl border bg-card p-4"><h2 className="font-semibold">{title}</h2>{children}</section>; }
function Evidence({ value, label = "View evidence" }: { value: unknown; label?: string }) { return <details className="text-sm"><summary className="cursor-pointer text-muted-foreground">{label}</summary><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap rounded bg-muted p-3 text-xs">{JSON.stringify(value, null, 2)}</pre></details>; }
function Empty({ children = "Nothing to show yet." }: { children?: ReactNode }) { return <p className="text-sm text-muted-foreground">{children}</p>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-1 text-sm"><span>{label}</span>{children}</label>; }

export function OperationsHub({ data, orgId, userId, role }: { data: HubData; orgId: string; userId: string; role: Role }) {
  const router = useRouter();
  const params = useSearchParams();
  const initialTab = params.get("tab") as Tab;
  const [tab, setTab] = useState<Tab>(tabs.includes(initialTab) ? initialTab : "Overview");
  const [busy, setBusy] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const [resourceId, setResourceId] = useState(data.resources[0]?.id ?? "");
  const [question, setQuestion] = useState("");
  const [filter, setFilter] = useState("");
  const [templateReview, setTemplateReview] = useState<{ id: string; configurationHash: string; review: { name: string; [key: string]: unknown }; status: string; resultMessage?: string } | null>(null);
  const [templateName, setTemplateName] = useState("");
  const [templateExposure, setTemplateExposure] = useState(false);
  const [templateConfirmation, setTemplateConfirmation] = useState("");
  const base = `/api/v1/orgs/${orgId}/operations`;
  const can = (permission: Parameters<typeof hasPermission>[1]) => hasPermission(role, permission);
  const resource = data.resources.find(r => r.id === resourceId);
  const records = (kind: RecordKind) => data.records.filter(r => r.kind === kind);
  const owners = new Set(records("OWNER").map(r => r.resourceId));
  const search = interpretInventorySearch(question);
  const filtered = data.resources.filter(r => `${r.name} ${r.resourceId} ${r.resourceType} ${r.awsAccount.displayName}`.toLowerCase().includes(filter.toLowerCase()));
  async function run(work: () => Promise<unknown>, message = "Saved") {
    setBusy(true);
    try { await work(); toast.success(message); router.refresh(); } catch (e) { toast.error(errorMessage(e)); } finally { setBusy(false); }
  }
  const save = (input: unknown) => run(() => api(base, { body: { command: "save", input } }));
  const action = (id: string, action: string) => run(() => api(`${base}/${id}`, { body: { action } }), "Request updated");
  function resourceSelect(name = "resourceId") { return <select name={name} className={control} required defaultValue={resourceId}>{data.resources.map(r => <option key={r.id} value={r.id}>{r.name ?? r.resourceId} · {r.awsAccount.displayName} · {r.region}</option>)}</select>; }
  function memberSelect(name: string, operations = false) { return <select name={name} className={control} required>{data.members.filter(m => !operations || hasPermission(m.role, "operations:manage")).map(m => <option key={m.userId} value={m.userId}>{m.user.name}</option>)}</select>; }
  function form(kind: RecordKind, children: ReactNode, payload: (f: FormData) => unknown) {
    if (!can(WRITE_PERMISSION[kind])) return null;
    return <form className="grid gap-3 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); try { void save({ kind, name: String(f.get("name")), ...(kind === "VIEW" ? { shared: f.get("shared") === "on" } : {}), payload: payload(f) }); } catch (error) { toast.error(errorMessage(error)); } }}>
      <Field label="Name"><Input name="name" required maxLength={100} /></Field>{children}<div className="sm:col-span-2"><Button disabled={busy}>Save</Button></div>
    </form>;
  }
  function removeButton(record: SavedItem) { return (record.userId === userId || can("org:update")) && can(WRITE_PERMISSION[record.kind]) ? <Button variant="ghost" size="sm" disabled={busy} onClick={() => void run(() => api(`${base}/${record.id}`, { method: "DELETE" }), "Removed")}>Remove</Button> : null; }
  function resourceLink(r: OpsResource) { return <Link className="font-medium hover:underline" href={resourceHref(r.resourceType, r.id, r.resourceId)}>{r.name ?? r.resourceId}</Link>; }
  return <div className="space-y-5">
    <div><h1 className="text-2xl font-semibold">Operations</h1><p className="text-sm text-muted-foreground">Understand changes, coordinate work, and review cloud actions.</p></div>
    <nav aria-label="Operations sections" className="flex flex-wrap gap-2">{tabs.map(t => <Button key={t} variant={tab === t ? "secondary" : "ghost"} onClick={() => setTab(t)} aria-pressed={tab === t}>{t}</Button>)}</nav>
    {data.truncated && <p role="status" className="rounded border p-3 text-sm">This overview is limited to 2,000 resources and 20,000 cost rows. Counts and comparisons apply only to loaded data; use the inventory and Cost Explorer for full details.</p>}
    {tab === "Overview" && <>
      <Box title="Action center">{data.priorities.actions.length ? data.priorities.actions.map(item => <div key={`${item.kind}:${item.id}`} className="border-t py-3"><Link href={item.href} className="font-medium hover:underline">{item.title}</Link><span className="ml-2 text-xs text-muted-foreground">{item.priority}</span><p className="text-sm text-muted-foreground">{item.reason}</p><Link href={`/help?${new URLSearchParams({ kind: item.kind, target: item.id })}`} className="text-sm underline">Assign follow-up in Team help</Link></div>) : <Empty>No current priority items in the available data.</Empty>}{data.help.slice(0, 10).map(h => <div key={h.id} className="flex flex-wrap items-center justify-between gap-2 border-t py-3"><div><p className="text-sm font-medium">{h.title} · {h.status}</p><p className="text-xs text-muted-foreground">Assigned to {h.assignee?.name ?? "a removed member"}</p></div>{(h.assigneeId === userId || h.requestedById === userId || can("org:update")) && <HelpStatus orgId={orgId} id={h.id} status={h.status} />}</div>)}<Link href="/help" className="text-sm underline">Manage assigned work ({data.help.filter(h => h.status !== "DONE").length} open)</Link></Box>
      <Box title="All cloud connections"><p className="text-sm text-muted-foreground">Provider snapshots retain their own coverage and billing definitions. No combined cross-currency total.</p><div className="grid gap-3 md:grid-cols-3"><div className="rounded border p-3"><Link href="/" className="font-medium underline">AWS</Link>{data.priorities.accounts.map(a => <p key={a.id} className="mt-2 text-sm">{a.displayName} · {a.syncStatus}<br /><span className="text-xs text-muted-foreground">{date(a.lastSyncedAt)}</span></p>)}{!data.priorities.accounts.length && <Empty>No accounts connected.</Empty>}</div>{(["GCP", "AZURE"] as const).map(provider => <div key={provider} className="rounded border p-3"><Link href={`/cloud/${provider.toLowerCase()}`} className="font-medium underline">{provider === "GCP" ? "Google Cloud" : "Microsoft Azure"}</Link>{data.clouds.filter(c => c.provider === provider).map(c => <div key={c.id} className="mt-2 text-sm"><p>{c.displayName} · {c.status}</p><p>{c.inventory === null ? "Inventory unavailable" : `${c.inventory.length} resources`} · {date(c.inventoryAt)}</p>{[...new Set(c.billing?.map(b => b.currency))].map(currency => <p key={currency}>{c.billing?.filter(b => b.currency === currency).reduce((sum, b) => sum + b.amount, 0).toFixed(2)} {currency} in available billing snapshot</p>)}<p className="text-xs">{provider === "GCP" ? "Usage cost excludes credits and invoice adjustments." : "Pre-tax cost; agreement-dependent coverage."}</p></div>)}{!data.clouds.some(c => c.provider === provider) && <Empty>No connections.</Empty>}</div>)}</div></Box>
      {can("inventory:read") && <Box title="Ask the inventory"><Field label="Describe the resources you need"><Input value={question} onChange={e => setQuestion(e.target.value)} placeholder="Running production servers without an owner" maxLength={200} /></Field><p className="text-xs text-muted-foreground">Understands servers, buckets, running/stopped, environment, region, and missing assigned owners. Review filters before opening; other words are not interpreted. Environment uses the env tag.</p>{question && <>{search.supported ? <><div className="flex flex-wrap gap-2">{Object.entries(search.filters).map(([key, value]) => <span key={key} className="rounded bg-muted px-2 py-1 text-xs">{key}: {value}</span>)}</div><Button asChild><Link href={`/resources?${new URLSearchParams(search.filters)}`}>Open filtered inventory</Link></Button></> : <Empty>No supported filters found. Try “running servers in us-east-1”.</Empty>}</>}</Box>}
    </>}
    {tab === "Resources" && can("inventory:read") && <>
      <Box title="Resource history and dependencies"><Field label="Resource"><select className={control} value={resourceId} onChange={e => setResourceId(e.target.value)}>{data.resources.map(r => <option key={r.id} value={r.id}>{r.name ?? r.resourceId} · {r.region}</option>)}</select></Field>{resource && <><p className="text-sm">Last observed {date(resource.lastSeenAt)} · {resource.awsAccount.syncStatus}</p><div className="grid gap-4 md:grid-cols-2"><div><h3 className="text-sm font-medium">Observed relationships</h3><p className="text-xs text-muted-foreground">Exact inventory references in this account and region. Application dependencies and traffic impact may be missing.</p>{relatedResources(resource, data.resources).map(r => <p key={r.id} className="mt-2 text-sm">{resourceLink(r)} · {r.resourceType}</p>)}{!relatedResources(resource, data.resources).length && <Empty>No relationships observed.</Empty>}</div><div><h3 className="text-sm font-medium">Change timeline</h3>{data.changes.filter(c => c.resourceId === resourceId).map(c => <div key={c.id} className="border-t py-2"><p className="text-sm">{c.kind} · {date(c.observedAt)}</p><Evidence value={{ before: c.before, after: c.after }} /></div>)}{!data.changes.some(c => c.resourceId === resourceId) && <Empty>No changes recorded since history was enabled.</Empty>}</div></div></>}</Box>
      <Box title="Recent inventory changes"><p className="text-xs text-muted-foreground">Latest 200 observed changes across the workspace, including deleted resources. Earlier changes remain stored.</p>{data.changes.slice(0, 30).map(c => <div key={c.id} className="border-t py-2 text-sm"><p>{String((c.after as { name?: string } | null)?.name ?? (c.before as { name?: string } | null)?.name ?? c.resourceId)} · {c.kind} · {date(c.observedAt)}</p><Evidence value={{ before: c.before, after: c.after }} /></div>)}</Box>
      <Box title="Resource ownership">{form("OWNER", <><Field label="Resource">{resourceSelect()}</Field><Field label="Owner"><Input name="owner" required maxLength={100} /></Field><Field label="Team"><Input name="team" maxLength={100} /></Field></>, f => ({ resourceId: f.get("resourceId"), owner: f.get("owner"), team: f.get("team") }))}{records("OWNER").map(item => <div key={item.id} className="flex flex-wrap justify-between gap-2 border-t py-2 text-sm"><span>{item.name}: {String(item.payload.owner)} · {String(item.payload.team || "No team")}</span>{removeButton(item)}</div>)}</Box>
      <Box title="Required tag coverage"><p className="text-sm">Required tags: {data.org.requiredTagKeys.join(", ") || "None configured"}. <Link href="/settings/workspace" className="underline">Change required tags</Link></p><Input aria-label="Filter resources" placeholder="Filter resources…" value={filter} onChange={e => setFilter(e.target.value)} />{filtered.filter(r => data.org.requiredTagKeys.some(key => !r.tags.some(t => t.key === key && t.value.trim()))).slice(0, 100).map(r => <div key={r.id} className="flex flex-wrap justify-between gap-2 border-t py-2 text-sm"><span>{resourceLink(r)} — missing {data.org.requiredTagKeys.filter(key => !r.tags.some(t => t.key === key && t.value.trim())).join(", ")}</span><Button size="sm" variant="outline" onClick={() => { setSelected([r.id]); setTab("Automation"); }}>Review bulk tags</Button></div>)}<p className="text-xs text-muted-foreground">Showing up to 100 matching resources. Edit individual tags from the resource page; supported EC2 resources can use reviewed bulk tagging.</p></Box>
      <Box title="Configuration drift">{form("BASELINE", <Field label="Resource">{resourceSelect()}</Field>, f => ({ resourceId: f.get("resourceId") }))}<p className="text-xs text-muted-foreground">Saving a baseline records current observed configuration and tags. Accepting drift replaces that baseline.</p>{data.baselines.map(b => <div key={b.id} className="space-y-2 border-t py-3"><p className="text-sm font-medium">{b.name}: {!b.observed ? "Resource unavailable in this view" : b.changes.length ? `Changed: ${b.changes.join(", ")}` : "Matches baseline"}</p><Evidence value={{ before: b.before, after: b.after }} />{b.observed && b.changes.length > 0 && can("operations:manage") && <Button size="sm" disabled={busy} onClick={() => { const r = data.records.find(r => r.id === b.id)!; void run(() => api(`${base}/${b.id}`, { method: "PATCH", body: { version: r.version, input: { kind: "BASELINE", name: r.name, payload: { resourceId: b.resourceId } } } })); }}>Accept current configuration</Button>}</div>)}</Box>
    </>}
    {tab === "Reliability" && can("inventory:read") && <>
      <Box title="Backup readiness"><p className="text-sm text-muted-foreground">Based on observed database retention and completed volume snapshots. “Configured” does not mean a restore has been tested.</p>{data.resources.filter(r => ["ec2:volume", "rds:db-instance"].includes(r.resourceType)).slice(0, 100).map(r => { const b = backupReadiness(r, data.resources); return <div key={r.id} className="border-t py-3 text-sm">{resourceLink(r)} · <strong>{b.status}</strong><p className="text-muted-foreground">{b.detail}</p><p className="text-xs">Observed {date(r.lastSeenAt)} · {r.awsAccount.syncStatus}</p></div>; })}{!data.resources.some(r => ["ec2:volume", "rds:db-instance"].includes(r.resourceType)) && <Empty>No supported volumes or databases in the available inventory.</Empty>}</Box>
      <Box title="Credential and certificate reminders">{data.credentials.map(a => <div key={a.id} className="border-t py-2"><p className="text-sm font-medium">{a.displayName} · key metadata observed {date(a.securityScannedAt)}</p>{a.securityCoverage?.credentialMetadata ? a.securityCoverage.credentialMetadata.filter(k => k.active).map((k, i) => <p key={i} className="text-sm">{k.userName} · {k.keyHint} · {k.ageDays} days old{k.ageDays >= 90 ? " — review rotation" : ""}</p>) : <Empty>Credential scan unavailable.</Empty>}</div>)}{data.resources.filter(r => typeof r.attributes.certificateValidTill === "string").map(r => <p key={r.id} className="text-sm">{resourceLink(r)} · observed certificate expiry {date(String(r.attributes.certificateValidTill))}</p>)}<p className="text-sm text-muted-foreground">Record a known certificate expiry or credential rotation deadline. Dates are supplied by your team; RDS certificate expiry is shown when collected. Due reminders appear in Alerts when the worker runs.</p>{form("REMINDER", <><Field label="Due date"><Input type="datetime-local" name="dueAt" required /></Field><Field label="Days before due date"><Input type="number" name="daysBefore" defaultValue={30} min={0} max={365} required /></Field><Field label="Notes"><Input name="note" maxLength={500} /></Field></>, f => ({ dueAt: new Date(String(f.get("dueAt"))).toISOString(), daysBefore: Number(f.get("daysBefore")), note: f.get("note") }))}{records("REMINDER").map(r => <div key={r.id} className="flex justify-between border-t py-2 text-sm"><span>{r.name} · due {date(String(r.payload.dueAt))} · remind {String(r.payload.daysBefore)} days before</span>{removeButton(r)}</div>)}</Box>
      <Box title="Environment health">{form("ENVIRONMENT", <><Field label="Tag key"><Input name="tagKey" defaultValue="env" required /></Field><Field label="Tag value"><Input name="tagValue" placeholder="production" required /></Field></>, f => ({ tagKey: f.get("tagKey"), tagValue: f.get("tagValue") }))}{records("ENVIRONMENT").map(env => { const rs = data.resources.filter(r => r.tags.some(t => t.key === env.payload.tagKey && t.value === env.payload.tagValue)); return <div key={env.id} className="border-t py-3"><div className="flex justify-between"><h3 className="font-medium">{env.name}</h3>{removeButton(env)}</div><p className="text-sm">{rs.length} resources · {rs.filter(r => !owners.has(r.id)).length} without assigned owners · {rs.filter(r => !r.awsAccount.lastSyncedAt || Date.now() - Date.parse(r.lastSeenAt) > 26 * 3600000 || r.awsAccount.syncStatus !== "SUCCEEDED").length} with stale or incomplete observations</p><p className="text-sm">{can("security:read") ? `${data.security.filter(f => rs.some(r => r.id === f.resourceRefId)).length} open resource-linked security findings in loaded data` : "Security findings are unavailable for this role"}</p><p className="text-xs text-muted-foreground">Resource state is not application uptime. Environment-level spend is unavailable without resource-level billing attribution.</p><Link className="text-sm underline" href={`/resources?${new URLSearchParams({ tag: `${env.payload.tagKey}=${env.payload.tagValue}` })}`}>Open environment resources</Link></div>; })}</Box>
    </>}
    {tab === "Costs" && can("cost:read") && <>
      <Box title="Cost spike explanations"><p className="text-sm text-muted-foreground">Latest reported day before today versus seven consecutive preceding days, per account and currency. Shows increases above 30% and daily spend of at least 10 currency units. Billing can be delayed or estimated.</p>{costSpikes(data.costs).map(s => <div key={`${s.accountId}:${s.currency}`} className="space-y-2 border-t py-3"><h3 className="font-medium">{data.priorities.accounts.find(a => a.id === s.accountId)?.displayName ?? s.accountId} · +{s.percent.toFixed(0)}%</h3><p className="text-sm">{s.day}: {s.amount.toFixed(2)} {s.currency} vs {s.average.toFixed(2)} daily average{s.estimated ? " (estimated billing)" : ""}</p>{s.services.map(v => <p key={v.service} className="text-sm">{v.service}: {v.amount.toFixed(2)} {s.currency} · {v.increase === null ? "Baseline unavailable" : `${v.increase.toFixed(2)} above daily baseline`}</p>)}</div>)}{!costSpikes(data.costs).length && <Empty>No spikes found with sufficient daily history. Missing data does not mean spending is stable.</Empty>}<Link href="/settings/alerts" className="text-sm underline">Configure cost anomaly alerts</Link></Box>
      <Box title="Savings outcome tracking">{form("SAVING", <Field label="Recommendation"><select name="findingId" className={control} required>{data.findings.map(f => <option key={f.id} value={f.id}>{f.title}</option>)}</select></Field>, f => ({ findingId: f.get("findingId") }))}<p className="text-sm text-muted-foreground">Compares seven days of whole-account costs before acceptance with seven days after. These changes cannot be attributed to one recommendation; traffic and other changes also affect spending.</p>{records("SAVING").map(r => { const result = data.savings.find(s => s.id === r.id); const baseline = r.payload.baseline as { currency: string; amount: number; days: number }[]; return <div key={r.id} className="space-y-2 border-t py-3"><h3 className="font-medium">{r.name}</h3><p className="text-sm">{result?.complete ? "Comparison window ended" : "Collecting the next seven days"}</p>{baseline.map(b => { const after = result?.after.find(v => v.currency === b.currency); return <p key={b.currency} className="text-sm">{b.currency}: baseline {b.amount.toFixed(2)} ({b.days}/7 days) → {after ? `${after.amount.toFixed(2)} (${after.days}/7 days)` : "No post-change data"}{after?.days === 7 && b.days === 7 ? `; observed decrease ${(b.amount - after.amount).toFixed(2)}` : "; insufficient coverage for a difference"}</p>; })}{!baseline.length && <Empty>No billing baseline available.</Empty>}</div>; })}</Box>
    </>}
    {tab === "Team" && <>
      {can("operations:manage") && <Box title="Incident workspace">{form("INCIDENT", <><Field label="Resource">{resourceSelect()}</Field><Field label="Assignee">{memberSelect("assigneeId", true)}</Field><Field label="Initial note"><Input name="note" required maxLength={4000} /></Field><Field label="Follow-up task"><Input name="task" maxLength={100} /></Field></>, f => ({ resourceIds: [f.get("resourceId")], assigneeId: f.get("assigneeId"), status: "OPEN", note: f.get("note"), tasks: f.get("task") ? [{ title: f.get("task"), done: false }] : [] }))}{records("INCIDENT").map(r => <Incident key={r.id} item={r} changes={data.changes} resources={data.resources} security={data.security} metrics={data.metrics} disabled={busy} update={(input) => void run(() => api(`${base}/${r.id}`, { method: "PATCH", body: { input, version: r.version } }))} />)}</Box>}
      {can("inventory:read") && <Box title="Workspace saved views"><p className="text-sm text-muted-foreground">Save a filtered inventory URL for your own use across devices, or share it with your workspace.</p>{form("VIEW", <><Field label="Inventory URL"><Input name="url" placeholder="/resources?state=running" defaultValue="/resources" required maxLength={6000} /></Field><label className="flex items-center gap-2 text-sm"><input name="shared" type="checkbox" disabled={!can("operations:manage")} />Share with workspace</label></>, f => { const url = new URL(String(f.get("url")), window.location.origin); if (url.origin !== window.location.origin) throw new Error("Use an inventory link from this app"); return { path: url.pathname, query: url.search.slice(1) }; })}{records("VIEW").map(r => <div key={r.id} className="flex justify-between border-t py-2 text-sm"><Link className="underline" href={`${r.payload.path}${r.payload.query ? `?${r.payload.query}` : ""}`}>{r.name} · {r.shared ? "Shared" : "Personal"}</Link>{removeButton(r)}</div>)}</Box>}
    </>}
    {tab === "Automation" && can("actions:request") && <>
      <Box title="Review bulk changes and scheduled shutdowns"><p className="text-sm text-muted-foreground">Choose resources, then create an immutable request for another administrator to approve. Nothing runs at creation. Start/stop schedules are one-time occurrences; add separate start and stop requests for a workday. Cancelling a request provides a schedule exception.</p><Input aria-label="Find resources to change" value={filter} onChange={e => setFilter(e.target.value)} placeholder="Find resources…" /><div className="max-h-64 overflow-auto rounded border p-2">{filtered.filter(r => r.resourceType.startsWith("ec2:")).slice(0, 200).map(r => <label key={r.id} className="flex items-center gap-2 py-1 text-sm"><input type="checkbox" checked={selected.includes(r.id)} onChange={e => setSelected(e.target.checked ? [...selected, r.id] : selected.filter(id => id !== r.id))} />{r.name ?? r.resourceId} · {r.state} · {r.region}</label>)}</div><p className="text-xs">{selected.length} selected (maximum 50)</p><form className="grid gap-3 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const tags = String(f.get("tags") ?? "").split("\n").filter(Boolean).map(line => { const i = line.indexOf("="); return { key: i < 0 ? line : line.slice(0, i), value: i < 0 ? "" : line.slice(i + 1) }; }); void run(() => api(base, { body: { command: "plan", input: { name: f.get("name"), resourceIds: selected, action: f.get("action"), tags, ...(f.get("scheduledAt") ? { scheduledAt: new Date(String(f.get("scheduledAt"))).toISOString() } : {}), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone } } }), "Request created for approval"); }}><Field label="Request name"><Input name="name" required maxLength={100} /></Field><Field label="Action"><select className={control} name="action"><option value="tag">Add or replace tags</option><option value="stop">Stop instances</option><option value="start">Start instances</option><option value="reboot">Reboot instances</option></select></Field><Field label="Tags, one key=value per line"><textarea name="tags" className={control} rows={3} placeholder="env=development" /></Field><Field label={`Optional start/stop time (${Intl.DateTimeFormat().resolvedOptions().timeZone})`}><Input type="datetime-local" name="scheduledAt" /></Field><Button disabled={busy || !selected.length || selected.length > 50}>Create review request</Button></form></Box>
      <Box title="Requests and execution receipts">{data.plans.map(p => <div key={p.id} className="space-y-3 border-t py-3"><h3 className="font-medium">{p.name} · {p.status}</h3><p className="text-sm">{p.payload.action} · {p.payload.snapshots.length} resources · {p.scheduledAt ? `Scheduled ${new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short", timeZone: p.payload.timezone }).format(new Date(p.scheduledAt))} (${p.payload.timezone})` : "Manual execution after approval"}</p><ul className="text-sm">{p.payload.snapshots.map(r => <li key={r.id}>{r.name} · {r.resourceId}</li>)}</ul>{p.payload.action === "tag" && <p className="text-sm">Set {p.payload.tags.map(t => `${t.key}=${t.value}`).join(", ")}. Other tag keys are preserved.</p>}<Evidence value={p.payload.snapshots} label="Review exact resource snapshots" /><p className="text-xs text-muted-foreground">Stopping or rebooting can interrupt workloads. Starting instances can incur charges. Approval expires {date(p.expiresAt)}.</p><div className="flex flex-wrap gap-2">{p.status === "PENDING" && can("org:update") && p.userId !== userId && <><Button disabled={busy} onClick={() => void action(p.id, "approve")}>Approve reviewed changes</Button><Button variant="outline" disabled={busy} onClick={() => void action(p.id, "reject")}>Reject</Button></>}{["PENDING", "APPROVED"].includes(p.status) && (p.userId === userId || can("org:update")) && <Button variant="outline" disabled={busy} onClick={() => void action(p.id, "cancel")}>Cancel request</Button>}{p.status === "APPROVED" && !p.scheduledAt && <Button disabled={busy} onClick={() => void action(p.id, "execute")}>Execute approved request</Button>}</div>{p.result !== null && <Evidence value={p.result} label="Execution receipt" />}</div>)}{!data.plans.length && <Empty>No requests created.</Empty>}</Box>
      {can("actions:configure") && <Box title="Configure the action role"><p className="text-sm text-muted-foreground">Owner only. Deploy a separate IAM action role in the selected account using its existing connection ExternalId. Grant only the EC2 describe, start, stop, reboot and tagging permissions you need. Enabling action mode applies to this workspace.</p><p className="text-sm">Action mode: {data.org.actionModeEnabled ? "Enabled" : "Disabled"}</p><form className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run(() => api(base, { body: { command: "configure", input: { accountId: f.get("accountId"), roleArn: f.get("roleArn"), enabled: f.get("enabled") === "on" } } })); }}><Field label="AWS account"><select name="accountId" className={control}>{data.priorities.accounts.map(a => <option key={a.id} value={a.id}>{a.displayName}</option>)}</select></Field><Field label="Separate action role ARN"><Input name="roleArn" required placeholder="arn:aws:iam::123456789012:role/StratusActions" /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="enabled" defaultChecked={data.org.actionModeEnabled} />Enable reviewed actions</label><Button disabled={busy}>Save action configuration</Button></form></Box>}
    </>}
    {tab === "Templates" && can("provisioning:create") && <Box title="Reusable provisioning templates"><p className="text-sm text-muted-foreground">Create a resource review and save its configuration as a template. Reusing a template runs current guardrails and generates a new plan for review before deployment.</p><div className="flex flex-wrap gap-2">{(["ec2", "s3", "vpc", "subnet"] as const).map(service => <CreateResource key={service} orgId={orgId} service={service} />)}</div><Field label="Name for the new resource (optional override)"><Input value={templateName} onChange={e => setTemplateName(e.target.value)} maxLength={63} /></Field>{records("TEMPLATE").map(r => <div key={r.id} className="space-y-2 border-t py-3"><h3 className="font-medium">{r.name}</h3><Evidence value={r.payload} label="Template configuration" /><Button disabled={busy} onClick={() => void run(async () => { const plan = await api<NonNullable<typeof templateReview>>(`${base}/${r.id}`, { body: { action: "template-plan", ...(templateName ? { name: templateName } : {}) } }); setTemplateReview(plan); setTemplateConfirmation(""); setTemplateExposure(false); }, "Review plan created")}>Create new review plan</Button>{removeButton(r)}</div>)}{templateReview && <div className="space-y-3 rounded border p-3"><h3 className="font-medium">Deployment review · {templateReview.status}</h3><Evidence value={templateReview.review} label="Review configuration, cost and guardrails" /><p className="text-sm">{templateReview.resultMessage}</p><Field label={`Type ${templateReview.review.name} to confirm`}><Input value={templateConfirmation} onChange={e => setTemplateConfirmation(e.target.value)} /></Field><label className="flex gap-2 text-sm"><input type="checkbox" checked={templateExposure} onChange={e => setTemplateExposure(e.target.checked)} />I acknowledge public network exposure if requested in this plan.</label><Button disabled={busy || templateReview.status !== "PLANNED" || templateConfirmation !== templateReview.review.name} onClick={() => void run(async () => setTemplateReview(await api(`/api/v1/orgs/${orgId}/provisioning/plans/${templateReview.id}/apply`, { body: { configurationHash: templateReview.configurationHash, confirmation: templateConfirmation, acknowledgeExposure: templateExposure } })), "Deployment request processed")}>Deploy reviewed template</Button></div>}</Box>}
    {tab === "Notifications" && can("alerts:manage") && <>
      <Box title="Email notifications"><p className="text-sm text-muted-foreground">Requires configured SMTP and a running worker. Recipients must be verified workspace members. Messages contain a sign-in link rather than resource details. Delivery retries may produce duplicate emails.</p>{form("NOTIFICATION", <><Field label="Recipient">{memberSelect("memberId")}</Field><Field label="Alert rule"><select name="ruleId" className={control}><option value="">All new alerts</option>{data.rules.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></Field></>, f => ({ memberId: f.get("memberId"), ...(f.get("ruleId") ? { ruleId: f.get("ruleId") } : {}), enabled: true }))}{records("NOTIFICATION").map(r => <div key={r.id} className="flex flex-wrap items-center justify-between gap-2 border-t py-3"><span className="text-sm">{r.name} · {data.members.find(m => m.userId === r.payload.memberId)?.user.name ?? "Member unavailable"}</span><div><Button disabled={busy} size="sm" onClick={() => void action(r.id, "test")}>Queue test email</Button>{removeButton(r)}</div></div>)}</Box>
      <Box title="Delivery history">{data.deliveries.map(d => <p key={d.id} className="border-t py-2 text-sm">{d.status} · {d.attempts} attempt(s) · {date(d.updatedAt)}<br />{d.message}</p>)}{!data.deliveries.length && <Empty>No deliveries queued yet.</Empty>}</Box>
    </>}
    {((tab === "Resources" || tab === "Reliability") && !can("inventory:read") || tab === "Costs" && !can("cost:read") || tab === "Automation" && !can("actions:request") || tab === "Templates" && !can("provisioning:create") || tab === "Notifications" && !can("alerts:manage")) && <Empty>Your role does not have access to this section.</Empty>}
    <p className="text-xs text-muted-foreground">History starts when this feature is installed. Scans observe changes but do not identify who made them. Scheduled operations and notifications require the worker.</p>
  </div>;
}

function Incident({ item, changes, resources, security, metrics, update, disabled }: { item: SavedItem; changes: Change[]; resources: OpsResource[]; security: HubData["security"]; metrics: HubData["metrics"]; update: (input: unknown) => void; disabled: boolean }) {
  const p = item.payload as { resourceIds: string[]; assigneeId: string; status: string; note: string; tasks: { title: string; done: boolean }[]; timeline: unknown[] };
  const [note, setNote] = useState("");
  const submit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault(); const f = new FormData(e.currentTarget);
    update({ kind: "INCIDENT", name: item.name, payload: { resourceIds: p.resourceIds, assigneeId: String(f.get("assigneeId") || p.assigneeId), status: f.get("status"), note, tasks: p.tasks.map((t, i) => ({ ...t, done: f.get(`task-${i}`) === "on" })) } });
  };
  return <article className="space-y-3 border-t pt-4"><h3 className="font-medium">{item.name} · {p.status}</h3><div className="flex flex-wrap gap-2">{resources.filter(r => p.resourceIds.includes(r.id)).map(r => <Link key={r.id} href={resourceHref(r.resourceType, r.id, r.resourceId)} className="text-sm underline">{r.name ?? r.resourceId}: open monitoring and findings</Link>)}</div><form className="space-y-2" onSubmit={submit}><select aria-label="Incident status" name="status" className={control} defaultValue={p.status}><option>OPEN</option><option>INVESTIGATING</option><option>RESOLVED</option></select>{p.tasks.map((task, i) => <label key={i} className="flex gap-2 text-sm"><input type="checkbox" name={`task-${i}`} defaultChecked={task.done} />{task.title}</label>)}<Input aria-label="Investigation note" value={note} onChange={e => setNote(e.target.value)} placeholder="Add investigation note" maxLength={4000} required /><Button disabled={disabled}>Update incident</Button></form><Evidence value={p.timeline} label="Investigation timeline" /><Evidence value={security.filter(f => p.resourceIds.includes(f.resourceRefId ?? ""))} label="Open security findings" /><Evidence value={metrics.filter(m => p.resourceIds.includes(m.resourceRefId))} label="Observed monitoring signals" /><Evidence value={changes.filter(c => p.resourceIds.includes(c.resourceId))} label="Recent resource changes" /></article>;
}
