import { createHash, randomBytes, timingSafeEqual } from "node:crypto";

/** URL-safe random token from the OS CSPRNG. */
export function randomToken(bytes = 32): string {
  return randomBytes(bytes).toString("base64url");
}

export function sha256Hex(input: string | Buffer): string {
  return createHash("sha256").update(input).digest("hex");
}

export function timingSafeEqualString(a: string, b: string): boolean {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) return false;
  return timingSafeEqual(ab, bb);
}

/**
 * Generates a per-connection ExternalId for sts:AssumeRole (confused-deputy protection).
 *
 * - 32 bytes (256 bits) from the CSPRNG → unguessable.
 * - base64url alphabet is a subset of AWS's allowed ExternalId charset [\w+=,.@:/-].
 * - Always generated by Stratus; customers can never choose it (AWS guidance).
 */
export function generateExternalId(): string {
  return `stratus-${randomBytes(32).toString("base64url")}`;
}

export const EXTERNAL_ID_PATTERN = /^stratus-[A-Za-z0-9_-]{43}$/;
